import { readdir, mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const source = path.resolve(root, '../expo-app/app');
const target = path.join(root, 'app');
// Only generated route wrappers live here; application code stays in expo-app.
await rm(target, { recursive: true, force: true });
async function visit(directory = '') {
  for (const entry of await readdir(path.join(source, directory), { withFileTypes: true })) {
    const relative = path.join(directory, entry.name);
    if (entry.isDirectory()) { await visit(relative); continue; }
    if (!/\.[jt]sx?$/.test(entry.name)) continue;
    const destination = path.join(target, relative);
    const implementation = relative === '_layout.tsx' ? path.join(root, 'components/RootLayout.tsx') : path.join(source, relative);
    let specifier = path.relative(path.dirname(destination), implementation).replaceAll(path.sep, '/').replace(/\.[jt]sx?$/, '');
    if (!specifier.startsWith('.')) specifier = './' + specifier;
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, `// Generated by prepare-routes.mjs. Edit the shared Expo route.\nexport { default } from ${JSON.stringify(specifier)};\nexport * from ${JSON.stringify(specifier)};\n`);
  }
}
await visit();
